// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQpm9F7_4NZruS0VQWNp7n0S9LYn8mY8',
    appId: '1:90071137086:android:c5c7984b2aed0ea295ca6f',
    messagingSenderId: '90071137086',
    projectId: 'instagramloginui-a18b1',
    storageBucket: 'instagramloginui-a18b1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxwhWKHZ5MpI72apCuqN7I1kqh6cW47g',
    appId: '1:90071137086:web:245c88b8bcd6d6a195ca6f',
    messagingSenderId: '90071137086',
    projectId: 'instagramloginui-a18b1',
    authDomain: 'instagramloginui-a18b1.firebaseapp.com',
    storageBucket: 'instagramloginui-a18b1.firebasestorage.app',
    measurementId: 'G-KR7LNDTXHC',
      databaseURL : 'https://instagramloginui-a18b1-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCoFPgM1aQGb-sdWGsgxeO8StvDB2QS_Y',
    appId: '1:90071137086:ios:58900a5cf12ef0d095ca6f',
    messagingSenderId: '90071137086',
    projectId: 'instagramloginui-a18b1',
    storageBucket: 'instagramloginui-a18b1.firebasestorage.app',
    iosBundleId: 'www.instagramui.com',
  );

}